import Config

# Configure your database
# Values fall back to native-friendly defaults; Docker compose overrides
# them via environment variables (POSTGRES_USER, POSTGRES_HOST, ...).
db_username = System.get_env("POSTGRES_USER") || System.get_env("USER") || "jidohyun"
db_password = System.get_env("POSTGRES_PASSWORD") || ""
db_hostname = System.get_env("POSTGRES_HOST") || "localhost"
db_port = String.to_integer(System.get_env("POSTGRES_PORT") || "5432")
db_database = System.get_env("POSTGRES_DB") || "auto_my_invoice_dev"

config :auto_my_invoice, AutoMyInvoice.Repo,
  username: db_username,
  password: db_password,
  hostname: db_hostname,
  port: db_port,
  database: db_database,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Phoenix bind address.
# Native dev defaults to loopback; Docker compose overrides with 0.0.0.0
# so that the host can reach the server on the published port.
phx_host_bind =
  (System.get_env("PHX_HOST_BIND") || "127.0.0.1")
  |> String.split(".")
  |> Enum.map(&String.to_integer/1)
  |> List.to_tuple()

config :auto_my_invoice, AutoMyInvoiceWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: phx_host_bind],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "MXSbaxkhjhGqMLh8dpz5UYPxfuvduR9WcSppqONM/7wKPXab7FKx5juz4QOXGNew",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:auto_my_invoice, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:auto_my_invoice, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :auto_my_invoice, AutoMyInvoiceWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/auto_my_invoice_web/router\.ex$"E,
      ~r"lib/auto_my_invoice_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :auto_my_invoice, dev_routes: true

# ChromicPDF: allow disabling Chrome sandbox in containerized dev environments.
# Default to no-sandbox so the dev server can boot inside Docker; native devs
# can override with CHROMIC_PDF_NO_SANDBOX=0 if their host Chrome supports it.
if System.get_env("CHROMIC_PDF_NO_SANDBOX", "1") in ~w(1 true yes) do
  config :auto_my_invoice, ChromicPDF, chrome_args: "--no-sandbox"
end

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
