import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :auto_my_invoice, AutoMyInvoiceWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# AMI-17: Force HTTPS + HSTS.
#
# * `rewrite_on: [:x_forwarded_proto]` — Fly.io / Render / nginx
#   terminate TLS at the edge and forward http inside the network.
#   Without this the redirect loop is infinite.
# * `hsts: true` + `expires: 31_536_000` + `subdomains: true`
#   + `preload: true` — opts the apex domain in to the HSTS preload
#   list (https://hstspreload.org). 1 year is the standard.
# * `exclude` — health checks must respond on plain HTTP because
#   load balancers probe before they know about TLS. Listing the
#   hosts plus the /health path keeps Fly.io's probe and curl
#   from the local network healthy.
#
# `:force_ssl` must be set at compile time — Plug.SSL is a compile-time
# plug. Per-deploy host/origin overrides happen in runtime.exs.
config :auto_my_invoice, AutoMyInvoiceWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    expires: 31_536_000,
    subdomains: true,
    preload: true,
    exclude: ["localhost", "127.0.0.1", "/health"]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
