defmodule AutoMyInvoiceWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :auto_my_invoice

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_auto_my_invoice_key",
    signing_salt: "bty4foSh",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :auto_my_invoice,
    gzip: not code_reloading?,
    only: AutoMyInvoiceWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :auto_my_invoice
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # AMI-14: stash raw body on conn.assigns[:raw_body] so the Paddle
    # webhook controller can recompute the HMAC-SHA256 signature
    # against the exact bytes Paddle signed. Without this, Plug.Parsers
    # consumes the body before the controller runs and signature
    # verification can never succeed.
    body_reader: {AutoMyInvoiceWeb.Plugs.RawBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # AMI-20: CORS for /api/* (v1 endpoints, webhooks, track). Other paths
  # are not browser-CORS-relevant (LiveView, server-rendered HTML).
  # Corsica picks up the origin list lazily via MFA so we never need to
  # recompile the endpoint to change it.
  plug Corsica,
    origins: [{AutoMyInvoiceWeb.Cors, :matches?}],
    allow_credentials: true,
    allow_headers: ["authorization", "content-type", "accept", "x-requested-with"],
    allow_methods: ~w(GET POST PUT PATCH DELETE OPTIONS),
    max_age: 600,
    log: [rejected: :warn]

  # AMI-19: attach request metadata (method, path, params, headers) to
  # any Sentry event raised below. No-op when SENTRY_DSN is unset.
  plug Sentry.PlugContext

  plug AutoMyInvoiceWeb.Router
end
